wandb_version: 1

seed:
  desc: null
  value: 42
data_path:
  desc: null
  value: ./dataset/tanjiaoyi/hb_carbon.csv
seq_len:
  desc: null
  value: 30
step:
  desc: null
  value: 1
threshold:
  desc: null
  value: 0.7
batch_size:
  desc: null
  value: 38
target:
  desc: null
  value: close
loader_path:
  desc: null
  value: ./dataset/tanjiaoyi/dataloader-38/hb-dataloader.pth
gcn_hidden_dim:
  desc: null
  value: 96
lstm_hidden_dim:
  desc: null
  value: 32
num_lstm_layers:
  desc: null
  value: 2
gru_hidden_dim:
  desc: null
  value: 64
num_gru_layers:
  desc: null
  value: 2
tcn_num_channels:
  desc: null
  value:
  - 64
  - 32
  - 16
tcn_kernel_size:
  desc: null
  value: 2
lr:
  desc: null
  value: 6.65601666979068e-05
num_node_features:
  desc: null
  value: 30
output_size:
  desc: null
  value: 1
num_epochs:
  desc: null
  value: 1000
dropout:
  desc: null
  value: 0.4
model:
  desc: null
  value: gc-tcn
model_path:
  desc: null
  value: ./checkpoints/DGCPN/
weight_name:
  desc: null
  value: 38-hb-loss&da-1000.pth
mc_samples:
  desc: null
  value: 200
prediction_interval:
  desc: null
  value: false
savefig_path:
  desc: null
  value: ./vis/GT-hb-1.png
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709188168.813586
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      - 100
      - 105
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      - 100
      - 105
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.8.18
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
